### ISSUE TITLE
ui-bug: Broken image src in Welcome message

### ISSUE THREAD

**Issue by luckyr13** [argoapp-live/beta-testing#30]
## Describe the bug
After succesful registration, there's a broken image pointing to: https://arweave.net/9ff_hVYLcNT0XGOndwmbQ3zdO1r1opSCOv61BDnb1tU/42.png

## Criticality
Low

## To Reproduce
1. A new user tries to register.
2. The new user mints the invitation token.
3. When the invitation is registered succesfully it receives a welcome message with an image. The image is broken.

## Expected behavior
Perhaps the image tx is not minted.
https://arweave.net/9ff_hVYLcNT0XGOndwmbQ3zdO1r1opSCOv61BDnb1tU/42.png

## Screenshots
![brokenImage](https://user-images.githubusercontent.com/7094823/164978765-40d92aff-e8a3-4891-a7e9-c5766b60739a.png)

## Desktop (please complete the following information):

 - OS: Windows 11
 - Browser: Chrome
 - Version: 100.0.4896.127 (Build oficial) (64 bits)
 - Location: Mexico

## Your Details
- Web3 Name: luckyr13
- Wallet Address (or ENS): 
- Twitter handle: criptoalfa

**Comment by rekpero** [comment]
Hey @luckyr13 this is due to the testnet NFT launch. We are not going to show how the art looks like right, it will be revealed once we launch the collection

**Comment by luckyr13** [comment]
Awesome! It makes sense now, thanks for your reply :)
