### ISSUE TITLE
ui-bug: (Nice to have) Redeploy button

### ISSUE THREAD

**Issue by luckyr13** [argoapp-live/beta-testing#31]
## Describe the bug
More than a bug is a nice to have. The older Spheron platform used to have a "Redeploy" button which makes easier and faster to redeploy projects. It would be awesome to have this button as well on the new aqua version.

## Criticality
Low

## To Reproduce
1. Create a new project
2. After the first deployment the project is available
3. If you enter into the project details there's no "Redeploy" button
4. To make a "Redeploy" user's needs to create a "New project", to me this was not so intuitive at first.

## Expected behavior
It would be cool to have a "Redeploy" button inside project detail.

## Screenshots
![spheronBefore](https://user-images.githubusercontent.com/7094823/164979984-aa76d23b-cf1b-48d9-8579-6d27db8c6b09.png)
![aquaAfter](https://user-images.githubusercontent.com/7094823/164980080-890ad9be-9a73-4e53-aeac-f678a41b1d86.png)

## Desktop (please complete the following information):
 - OS: Windows 11
 - Browser: Chrome
 - Version: --
 - Location: Mexico

## Your Details
- Web3 Name: luckyr13
- Wallet Address (or ENS): 
- Twitter handle: criptoalfa

**Comment by rekpero** [comment]
Yes, we are going to add it in our upcoming release which is very soon. 

Thanks, @luckyr13 for reporting. appreciate your support man!!!

**Comment by rekpero** [comment]
Hey, @luckyr13 we have added the redeploy feature in the recent release. Please check it out!!

**Comment by luckyr13** [comment]
Big Thank you!!! I can see it now!! I love this feature, thank you 🙏
