### ISSUE TITLE
Favicon not visible in browser tab

### ISSUE THREAD

**Issue by tommaay** [argoapp-live/beta-testing#5]
## Describe the bug
I successfully deployed a static Next.js app to Arweave and when I went to the deployed site, the favicon is not visible in the browser tab.

## Criticality
2 - favicon needs to work for production sites

## To Reproduce
1. Create a Next.js app
2. Create a favicon image that is 64x64 pixels and name it `favicon.ico` or use Next.js default favicon
3. Place that favicon in the directory `/public`
4. Deploy the site and select arweave
5. Once deployed visit the site and see if the favicon is visible

## Expected behavior
The favicon should appear in the browser tab

## Screenshots
<img width="168" alt="Screen Shot 2022-04-22 at 7 18 19 AM" src="https://user-images.githubusercontent.com/26946743/164734178-4ed82715-f67a-431f-9e1d-6b978c954077.png">

## Desktop (please complete the following information):
 - OS: macOs Monterey - 12.3.1 
 - Browser: Chrome
 - Version: 100.0.4896.127

## Additional context
I'm not sure if this is a bug or something I need to configure to get the favicon to work. But I'm used to the Vercel user experience so it would be nice to keep that same experience with ArGo

## Your Details
- Web3 Name: Tomster
- Twitter handle: 0xTomster

**Comment by rekpero** [comment]
I think this might be due to an application-level issue. We don't update anything on the app level like meta, favicon, etc.

Please test it on another platform and check if it's an application-level issue. Report it here with your result.

**Comment by tommaay** [comment]
It works fine on Vercel but sorry looks like I was testing in the wrong app: https://app.spheron.network/
