### ISSUE TITLE
Background video not playing for deployed website

### ISSUE THREAD

**Issue by tommaay** [argoapp-live/beta-testing#6]
## Describe the bug
I successfully deployed a static Next.js website to Arweave and it has a background video but it is not working on the deployed site.

## Criticality
2 - There's a fallback to the background color or image but I expect this to work at least on web browsers.

## To Reproduce
1. Create a Next.js app
2. Add a background video to the app.
4. Deploy the site and select arweave
5. Once deployed visit the site and see if the background video is playing.

## Expected behavior
The video should play in the background

## Desktop (please complete the following information):
 - OS: macOs Monterey - 12.3.1 
 - Browser: Chrome
 - Version: 100.0.4896.127

## Additional context
I'm using Tailwind CSS for styling and here is the code below where the video background is set.

```
const Layout = ({ title, keywords, description, children }) => {
  return (
    <div className="min-h-screen bg-darkblue text-white font-main overflow-x-hidden">
      <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
        <meta name="keywords" content={keywords} />
      </Head>

      <video
        loop
        autoPlay
        muted
        className="h-screen w-screen object-cover fixed -z-10"
      >
        <source src="/videos/bg-video.mp4" type="video/mp4" />
      </video>

      <Navbar />
      <div className="content-container">{children}</siv>
      <Footer />
    </div>
  )
}
```

## Your Details
- Web3 Name: Tomster
- Twitter handle: 0xTomster

**Comment by rekpero** [comment]
can you share a link to your deployed app which contains a background video? @tommaay

**Comment by tommaay** [comment]
Sorry looks like I was testing in the wrong app: https://app.spheron.network/
