### ISSUE TITLE
Automatic deployment did not trigger after a code push

### ISSUE THREAD

**Issue by tommaay** [argoapp-live/beta-testing#7]
## Describe the bug
I deployed a Next.js website using ArGo app to Arweave with the continuous deployment option checked. I then made a change and pushed that change to the repo which should have triggered an automatic deployment but it did not.

## Criticality
2 - I can manually deploy as a workaround but that's not fun.

## To Reproduce
1. Create a Next.js app
2. Deploy it with the continuous deployment option checked and select Arweave.
3. Make a change a push that change to the deployed repo.
4. Check if that triggered and automatic deployment.

## Expected behavior
A deployment should have started

## Desktop (please complete the following information):
 - OS: macOs Monterey - 12.3.1 
 - Browser: Chrome
 - Version: 100.0.4896.127

## Your Details
- Web3 Name: Tomster
- Twitter handle: 0xTomster

**Comment by rekpero** [comment]
Which UI are you testing? We don't have a continuous deployment option checkbox in our new web app.

Please test it on https://aqua.spheron.network

**Comment by tommaay** [comment]
Sorry looks like I was testing in the wrong app: https://app.spheron.network/
